apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "hello-chart.fullname" . }}
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ include "hello-chart.fullname" . }}
            servicePort: {{ .Values.service.port }}
