apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hello-chart.fullname" . }}-init-db
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "hello-chart.fullname" . }}
      labels:
        {{- include "hello-chart.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_URL
        command:
          - sh
          - "-c"
          - |
            python manage.py migrate
