# Default values for hello-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: vbeliakou/crud-app
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1

service:
  type: ClusterIP
  port: 8000

postgresql:
  enables: true
  postgresqlUsername: appuser
  postgresqlPassword: admin123
  postgresqlDatabase: appdb
  postgresqlPort: "5432"

ingress:
  host: arch.homework
  path: /otusapp/vbeliakou($|/)(.*)


